### ISSUE TITLE
An error is thrown while the bank selection is set on off, using iDEAL in the Hyvä Checkout

### ISSUE THREAD

**Issue by DennisVendic** [paynl/magento2-hyva-checkout#2]
### Summary
When having the settings **"Show bank selection" set on off** in Payment Methods > iDEAL, the module gives an error in the Hyvä checkout when trying to submit an order using iDEAL in live and test mode.

### Requirements
- PayNL Module: Version 3.11.1
- Magento: ver. 2.4.6-p4
- paynl/magento2-hyva-checkout": "^1.0"
- Hyvä Checkout 1.1.12
- Default Hyvä Theme 1.3.5
- In the configuration settings the payment methode iDEAL should have the settings "Show bank selection" set on "OFF"
![image](https://github.com/paynl/magento2-hyva-checkout/assets/100120970/da689cbd-691f-4f4c-abdc-928dd16ca7b9)

### Steps to reproduce
1. Add a product to the cart
2. Proceed to the checkout
3. Filling in the address and contact details
4. Select iDEAL
5. Submit the order
6. An error appears

### Expected results
You should be redirected to the page with the overview of all the banks.
![image](https://github.com/paynl/magento2-hyva-checkout/assets/100120970/17c16601-e078-4b4f-ac97-2571b07d5179)

### Actual result
An error appears, and you cannot select a bank.
![image](https://github.com/paynl/magento2-hyva-checkout/assets/100120970/961c96f8-fa17-4cba-bbe9-72a9dd70bf75)

**Comment by woutse** [comment]
Hi, thanks for your message. We'll look into it!

**Comment by annevelden** [comment]
Hello, this issue has been resolved in release 1.1.1. Thanks again for reporting.
