### ISSUE TITLE
Enhanced Payment Method Image Icon Rendering

### ISSUE THREAD

**Issue by RickDBCN** [paynl/magento2-hyva-checkout#9]
When upgrading to Hyva Checkout >= 1.1.22 the payment icons break.
https://gitlab.hyva.io/hyva-checkout/checkout/-/merge_requests/277
![image](https://github.com/user-attachments/assets/53062361-c3d2-41de-a7da-55f6d1c4cba8)

**Comment by woutse** [comment]
Thanks for your message. Fixed in release 1.2.0.
